Repository laminas/laminas-view, pull requests merged in 2021-03, with the labels that each got.

#69 Fix CI pipeline according to newer test dependency requirements
  .github/workflows/continuous-integration.yml
  .gitignore
  .travis.yml
  README.md
  composer.json
  composer.lock
  test/Helper/DoctypeTest.php
  test/Helper/EscapeCssTest.php
  test/Helper/EscapeHtmlAttrTest.php
  test/Helper/EscapeHtmlTest.php
  test/Helper/EscapeJsTest.php
  test/Helper/EscapeUrlTest.php
  test/Helper/EscaperEncodingsTrait.php
  test/Helper/GravatarTest.php
  test/Helper/HeadLinkTest.php
  test/Helper/HeadMetaTest.php
  test/Helper/HeadScriptTest.php
  test/Helper/HeadStyleTest.php
  test/Helper/Navigation/BreadcrumbsTest.php
  test/Helper/Navigation/MenuTest.php
  test/Helper/PartialLoopTest.php
  test/Helper/Placeholder/RegistryTest.php
Labels: Bug, Enhancement

#64 Fix tests without assertions
  test/Helper/DoctypeTest.php
  test/Helper/EscapeCssTest.php
  test/Helper/EscapeHtmlAttrTest.php
  test/Helper/EscapeHtmlTest.php
  test/Helper/EscapeJsTest.php
  test/Helper/EscapeUrlTest.php
  test/Helper/EscaperEncodingsTrait.php
  test/Helper/GravatarTest.php
  test/Helper/HeadLinkTest.php
  test/Helper/HeadMetaTest.php
  test/Helper/HeadScriptTest.php
  test/Helper/HeadStyleTest.php
  test/Helper/Navigation/BreadcrumbsTest.php
  test/Helper/Navigation/MenuTest.php
  test/Helper/PartialLoopTest.php
  test/Helper/Placeholder/RegistryTest.php
Labels: Enhancement

#66 Missing dev dependencies causing tests to fail
  composer.json
Labels: Bug

#67 Switch to GHA CI Setup
  .github/workflows/continuous-integration.yml
  .gitignore
  .travis.yml
  README.md
  composer.lock
Labels: Enhancement
