Repository laminas/laminas-view, pull requests merged in 2021-12, with the labels that each got.

#89 Re-enable skipped tests and improve type coverage
  .gitattributes
  .laminas-ci.json
  composer.json
  polyfill/Filter/FilterChain.php
  polyfill/FlashMessenger/FlashMessenger.php
  polyfill/Navigation/AbstractContainer.php
  polyfill/Paginator/ArrayAdapter.php
  polyfill/Paginator/Paginator.php
  polyfill/autoload.php
  psalm-baseline.xml
  src/Exception/ExceptionInterface.php
  test/Helper/AbstractHtmlElementTest.php
  test/Helper/AssetTest.php
  test/Helper/CycleTest.php
  test/Helper/DeclareVarsTest.php
  test/Helper/DoctypeTest.php
  test/Helper/EscapeCssTest.php
  test/Helper/EscapeHtmlAttrTest.php
  test/Helper/EscapeHtmlTest.php
  test/Helper/EscapeJsTest.php
  test/Helper/EscapeUrlTest.php
  test/Helper/FlashMessengerTest.php
  test/Helper/GravatarTest.php
  test/Helper/HeadLinkTest.php
  test/Helper/HeadMetaTest.php
  test/Helper/HeadScriptTest.php
  test/Helper/HeadStyleTest.php
  test/Helper/HeadTitleTest.php
  test/Helper/HtmlFlashTest.php
  test/Helper/HtmlListTest.php
  test/Helper/HtmlObjectTest.php
  test/Helper/HtmlPageTest.php
  test/Helper/HtmlQuicktimeTest.php
  test/Helper/HtmlTagTest.php
  test/Helper/InlineScriptTest.php
  test/Helper/JsonTest.php
  test/Helper/LayoutTest.php
  test/Helper/Navigation/LinksTest.php
  test/Helper/Navigation/NavigationTest.php
  test/Helper/Navigation/PluginManagerCompatibilityTest.php
  test/Helper/PaginationControlTest.php
  test/Helper/PartialLoopTest.php
  test/Helper/PartialTest.php
  test/Helper/Placeholder/ContainerTest.php
  test/Helper/Placeholder/RegistryTest.php
  test/Helper/Placeholder/StandaloneContainerTest.php
  test/Helper/PlaceholderTest.php
  test/Helper/ServerUrlTest.php
  test/Helper/TestAsset/IdentityObject.php
  test/HelperPluginManagerCompatibilityTest.php
  test/HelperPluginManagerTest.php
  test/Model/ConsoleModelTest.php
  test/Model/ViewModelTest.php
  test/PhpRendererTest.php
  test/Renderer/JsonRendererTest.php
  test/Resolver/TemplatePathStackTest.php
  test/Strategy/FeedStrategyTest.php
  test/Strategy/JsonStrategyTest.php
  test/ViewTest.php
  test/autoload.php
Labels: Enhancement, hacktoberfest-accepted

#96 Replace `container-interop/container-interop` with `psr/container`
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Helper/Navigation/PluginManager.php
  src/Helper/Service/AssetFactory.php
  src/Helper/Service/IdentityFactory.php
  src/HelperPluginManager.php
  test/Helper/Navigation/NavigationTest.php
  test/Helper/Service/DoctypeFactoryTest.php
Labels: Enhancement

#91 Declare `@deprecated` on the stream wrapper functionality (will be removed in `3.0.0`)
  src/Resolver/TemplatePathStack.php
  src/Stream.php
  test/Resolver/TemplatePathStackTest.php
Labels: Documentation, Enhancement

#97 Deprecate JsonExpressionFinder usage in Json View Helper
  docs/book/helpers/json.md
  src/Helper/Json.php
  test/Helper/JsonTest.php
Labels: Enhancement, Feature Removal
