Repository laminas/laminas-view, pull requests merged in 2022-01, with the labels that each got.

#102 Deprecate obsolete helpers
  docs/book/helpers/html-object.md
  src/Helper/HtmlFlash.php
  src/Helper/HtmlQuicktime.php
  src/HelperPluginManager.php
  test/Helper/HtmlFlashTest.php
  test/Helper/HtmlQuicktimeTest.php
Labels: Feature Removal

#101 Deprecates `ConsoleModel` and `ConsoleRenderer` for removal in `3.0.0`
  src/Model/ConsoleModel.php
  src/Renderer/ConsoleRenderer.php
  test/Model/ConsoleModelTest.php
Labels: Feature Removal

#95 Removes all outdated polyfills for related components, dropped PHP 7.3 support
  composer.json
  composer.lock
  polyfill/Filter/FilterChain.php
  polyfill/FlashMessenger/FlashMessenger.php
  polyfill/Navigation/AbstractContainer.php
  polyfill/Paginator/ArrayAdapter.php
  polyfill/Paginator/Paginator.php
  polyfill/autoload.php
  psalm-baseline.xml
  src/Helper/Navigation/PluginManager.php
  src/HelperPluginManager.php
  test/Model/TestAsset/Variable.php
Labels: Enhancement

#104 Cache and Session packages are not used anywhere
  composer.json
  composer.lock
  phpunit.xml.dist
Labels: Awaiting Author Updates, Enhancement

#107 Remove Irrelevant MVC 2 Compat
  composer.json
  psalm-baseline.xml
  src/Helper/FlashMessenger.php
  src/Helper/Url.php
  test/Helper/FlashMessengerTest.php
  test/HelperPluginManagerCompatibilityTest.php
Labels: Enhancement

#108 Remove Service Manager v2 Compatibility
  psalm-baseline.xml
  src/Helper/Navigation/AbstractHelper.php
  src/Helper/Navigation/PluginManager.php
  src/Helper/Service/AssetFactory.php
  src/Helper/Service/FlashMessengerFactory.php
  src/Helper/Service/IdentityFactory.php
  test/Helper/Navigation/BreadcrumbsTest.php
  test/Helper/Navigation/LinksTest.php
  test/Helper/Navigation/PluginManagerCompatibilityTest.php
  test/HelperPluginManagerTest.php
Labels: Awaiting Maintainer Response, Enhancement

#106 Update locked deps
  composer.lock
  psalm-baseline.xml
  src/Resolver/TemplatePathStack.php
  test/Resolver/TemplatePathStackTest.php
Labels: Enhancement

#111 Apply php 7.4 syntax + typed properties
  CHANGELOG.md
  psalm-baseline.xml
  src/Helper/HeadScript.php
  src/Helper/HeadTitle.php
  src/Helper/HtmlTag.php
  src/Helper/PartialLoop.php
  src/Helper/Placeholder/Container/AbstractStandalone.php
  src/HtmlAttributesSet.php
  src/Resolver/PrefixPathStackResolver.php
  src/Resolver/RelativeFallbackResolver.php
  src/Variables.php
  src/View.php
  test/Helper/DeclareVarsTest.php
  test/Helper/EscapeCssTest.php
  test/Helper/EscapeHtmlAttrTest.php
  test/Helper/EscapeHtmlTest.php
  test/Helper/EscapeJsTest.php
  test/Helper/EscapeUrlTest.php
  test/Helper/FlashMessengerTest.php
  test/Helper/HeadMetaTest.php
  test/Helper/HeadStyleTest.php
  test/Helper/HtmlAttributesTest.php
  test/Helper/HtmlListTest.php
  test/Helper/HtmlObjectTest.php
  test/Helper/HtmlPageTest.php
  test/Helper/HtmlQuicktimeTest.php
  test/Helper/HtmlTagTest.php
  test/Helper/JsonTest.php
  test/Helper/LayoutTest.php
  test/Helper/Navigation/AbstractTest.php
  test/Helper/Navigation/LinksTest.php
  test/Helper/Navigation/NavigationTest.php
  test/Helper/Navigation/SitemapTest.php
  test/Helper/PaginationControlTest.php
  test/Helper/RenderChildModelTest.php
  test/Helper/RenderToPlaceholderTest.php
  test/Helper/TestAsset/Aggregate.php
  test/Helper/TestAsset/ToArrayTest.php
  test/Helper/UrlIntegrationTest.php
  test/Helper/UrlTest.php
  test/HelperPluginManagerCompatibilityTest.php
  test/HelperPluginManagerTest.php
  test/HtmlAttributesSetTest.php
  test/PhpRendererTest.php
  test/Renderer/FeedRendererTest.php
  test/Renderer/JsonRendererTest.php
  test/Resolver/PrefixPathStackResolverTest.php
  test/Resolver/TemplatePathStackTest.php
  test/Strategy/FeedStrategyTest.php
  test/Strategy/JsonStrategyTest.php
  test/Strategy/PhpRendererStrategyTest.php
  test/TestAsset/SharedInstance.php
  test/VariablesTest.php
  test/ViewTest.php
Labels: Enhancement

#114 Update `composer.lock` and remove `CHANGELOG.md`, to prevent issues with future merge-up PRs
  CHANGELOG.md
  composer.lock
Labels: Bug

#113 Declare required PHP extensions
  .laminas-ci.json
  composer.json
  composer.lock
Labels: Enhancement

#118 Workaround for Cyclic Incompatible Dependencies on 3.0.x
  .laminas-ci/pre-install.sh
Labels: Bug

#125 Remove dependency on laminas-json
  composer.json
  composer.lock
  docs/book/helpers/json.md
  psalm-baseline.xml
  src/Helper/Json.php
  src/Model/JsonModel.php
  src/Renderer/JsonRenderer.php
  test/Helper/JsonTest.php
  test/Model/JsonModelTest.php
Labels: BC Break, Enhancement

#127 Removes deprecated/obsolete Flash and QuickTime helpers
  docs/book/helpers/html-object.md
  src/Helper/HtmlFlash.php
  src/Helper/HtmlQuicktime.php
  src/HelperPluginManager.php
  test/Helper/HtmlFlashTest.php
  test/Helper/HtmlQuicktimeTest.php
Labels: BC Break, Enhancement
