Repository laminas/laminas-view, pull requests merged in 2023-10, with the labels that each got.

#216 Initial 'Preparing for v3' docs
  docs/book/v2/migration/preparing-for-v3.md
  mkdocs.yml
Labels: Documentation

#212 Deprecations and type inference improvements for template resolvers
  psalm-baseline.xml
  src/Resolver/AggregateResolver.php
  src/Resolver/PrefixPathStackResolver.php
  src/Resolver/RelativeFallbackResolver.php
  src/Resolver/ResolverInterface.php
  src/Resolver/TemplateMapResolver.php
  src/Resolver/TemplatePathStack.php
  test/Resolver/AggregateResolverTest.php
  test/Resolver/TemplatePathStackTest.php
Labels: Documentation, Documentation Needed, Enhancement

#220 Add return type hint to ViewModel::getIterator()
  src/Model/ViewModel.php
Labels: Documentation, Enhancement

#221 Minor type inference improvements to ViewModel and ModelInterface
  psalm-baseline.xml
  src/Model/ModelInterface.php
  src/Model/RetrievableChildrenInterface.php
  src/Model/ViewModel.php
Labels: Documentation, Enhancement
