Repository laminas/laminas-view, pull requests merged in 2024-01, with the labels that each got.

#231 Updates wrong link in documentation for view event
  docs/book/v2/view-event.md
Labels: Bug, Documentation

#234 Upgrade to Psalm 5.20.x
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml.dist
  src/Helper/Doctype.php
  src/Helper/Gravatar.php
  src/Helper/HeadLink.php
  src/Helper/HeadScript.php
  src/Helper/Navigation/PluginManager.php
  src/Helper/ServerUrl.php
  src/Helper/Url.php
  src/HelperPluginManager.php
  src/Model/FeedModel.php
  src/Renderer/FeedRenderer.php
  src/Renderer/PhpRenderer.php
  src/Resolver/AggregateResolver.php
  src/Resolver/PrefixPathStackResolver.php
  src/Resolver/RelativeFallbackResolver.php
  test/Helper/DoctypeTest.php
  test/Helper/HtmlTagTest.php
  test/Helper/InlineScriptTest.php
  test/Helper/Navigation/LinksTest.php
  test/Helper/PaginationControlTest.php
  test/Helper/Placeholder/RegistryTest.php
  test/HelperPluginManagerCompatibilityTest.php
  test/Resolver/TemplatePathStackTest.php
  test/VariablesTest.php
Labels: Enhancement

#122 Initial work on a migration guide for 3
  docs/book/v3/migration/v2-to-v3.md
  mkdocs.yml
Labels: Documentation, Enhancement

#237 Deprecate the JSON View Helper for Removal in v3.0
  docs/book/v2/helpers/json.md
  docs/book/v2/migration/preparing-for-v3.md
  psalm-baseline.xml
  src/Helper/Json.php
  test/Helper/JsonTest.php
Labels: Documentation
