Repository laminas/laminas-view, pull requests merged in 2025-07, with the labels that each got.

#347 Update migration guide and `Partial` helper documentation
  docs/book/v3/helpers/partial.md
  docs/book/v3/migration/v2-to-v3.md
Labels: Documentation, Enhancement

#351 Ensure Invokable Variables are not Invoked
  test/Renderer/PhpRendererTest.php
  test/Renderer/templates/invokable-variable.phtml
Labels: BC Break, Enhancement, QA

#353 Deprecate `Variables`
  psalm-baseline.xml
  src/Variables.php
Labels: Feature Removal
