Repository laminas/laminas-view, pull requests merged in 2025-06, with the labels that each got.

#333 Refactor documentation to standardize callout formatting
  docs/book/v3/helpers/asset.md
  docs/book/v3/helpers/base-path.md
  docs/book/v3/helpers/intro.md
  docs/book/v3/helpers/partial.md
  docs/book/v3/php-renderer.md
Labels: Documentation, Enhancement

#334 Remove `ViewModel` "Options"
  psalm-baseline.xml
  src/Model/ClearableModelInterface.php
  src/Model/ModelInterface.php
  src/Model/ViewModel.php
  src/Renderer/PhpRenderer.php
  test/Model/ViewModelTest.php
Labels: BC Break, Feature Removal

#336 Deprecate "Options" for `ViewModel`
  psalm-baseline.xml
  src/Model/ClearableModelInterface.php
  src/Model/ModelInterface.php
  src/Model/ViewModel.php
Labels: Documentation, Feature Removal

#335 Update migration guide to note options removal from `ViewModel`
  docs/book/v3/migration/v2-to-v3.md
Labels: Documentation

#337 Remove `TreeRendererInterface`
  docs/book/v3/migration/v2-to-v3.md
  psalm-baseline.xml
  src/Renderer/PhpRenderer.php
  src/Renderer/TreeRendererInterface.php
  test/Helper/RenderChildModelTest.php
  test/PhpRendererTest.php
Labels: BC Break, Documentation, Feature Removal

#338 Partial Refactor of `Variables` with BC Breaking Changes to `RendererInterface`
  psalm-baseline.xml
  src/Exception/UndefinedVariableException.php
  src/Helper/Partial.php
  src/Helper/PartialLoop.php
  src/Model/ClearableModelInterface.php
  src/Model/ModelInterface.php
  src/Model/ViewModel.php
  src/Renderer/PhpRenderer.php
  src/Renderer/RendererInterface.php
  src/Variables.php
  test/Model/ViewModelTest.php
  test/PhpRendererTest.php
  test/TestAsset/VariableFunctor.php
  test/VariablesTest.php
Labels: BC Break, Enhancement, Feature Removal, QA

#339 Document Deprecations
  psalm-baseline.xml
  src/HelperPluginManager.php
  src/Model/JsonModel.php
  src/Renderer/JsonRenderer.php
  src/Renderer/PhpRenderer.php
  src/Renderer/RendererInterface.php
  src/Renderer/TreeRendererInterface.php
  src/Strategy/JsonStrategy.php
  src/Strategy/PhpRendererStrategy.php
  src/View.php
  src/ViewEvent.php
Labels: Documentation, Feature Removal

#340 Refactor template rendering
  psalm-baseline.xml
  src/ConfigProvider.php
  src/Exception/RenderingFailedException.php
  src/Exception/UnexpectedValueException.php
  src/Renderer/PhpRenderer.php
  src/Renderer/PhpRendererFactory.php
  src/Renderer/RendererInterface.php
  src/Renderer/Template.php
  test/Helper/PartialTest.php
  test/Helper/_files/modules/application/views/scripts/partialOne.phtml
  test/Helper/_files/modules/application/views/scripts/partialThree.phtml
  test/Helper/_files/modules/application/views/scripts/partialVars.phtml
  test/Helper/partial-templates/basic-variable.phtml
  test/Helper/partial-templates/iterate-over-variables.phtml
  test/Helper/partial-templates/static-content.phtml
  test/PhpRendererTest.php
  test/Renderer/PhpRendererTest.php
  test/Renderer/templates/call-invokable-helper.phtml
  test/Renderer/templates/call-uninvokable-helper.phtml
  test/Renderer/templates/escaped-variable.phtml
  test/Renderer/templates/exceptional-helper.phtml
  test/Renderer/templates/infinite-render-loop.phtml
  test/Renderer/templates/local-exception.phtml
  test/Renderer/templates/shared-helper.phtml
  test/Renderer/templates/static-content.phtml
  test/Renderer/templates/undefined-helper.phtml
  test/Renderer/templates/undefined-variable-condition.phtml
  test/Renderer/templates/variable-as-property.phtml
  test/Renderer/templates/variable-in-local-scope.phtml
  test/Renderer/templates/variable-mutation.phtml
  test/TestAsset/Uninvokable.php
  test/_templates/block.phtml
  test/_templates/exception.phtml
  test/_templates/layout.phtml
  test/_templates/test-with-helpers.phtml
  test/_templates/test.phtml
  test/_templates/testLocalVars.phtml
  test/_templates/testNestedInner.phtml
  test/_templates/testNestedOuter.phtml
  test/_templates/testStrictVars.phtml
  test/_templates/testSubTemplate.phtml
  test/_templates/testZf995.phtml
  test/_templates/view-model-variables.phtml
Labels: BC Break, Review Needed

#341 Deprecations for `PhpRenderer`
  psalm-baseline.xml
  src/Exception/UnexpectedValueException.php
  src/Renderer/PhpRenderer.php
Labels: Documentation, Feature Removal

#344 Further duck-typing deprecations + SA issue reduction
  bin/templatemap_generator.php
  psalm-baseline.xml
  src/Helper/Escaper/AbstractHelper.php
  src/Renderer/Template.php
  test/Helper/EscapeCssTest.php
  test/Helper/EscapeHtmlAttrTest.php
  test/Helper/EscapeHtmlTest.php
  test/Helper/EscapeJsTest.php
  test/Helper/EscapeUrlTest.php
  test/Helper/HtmlListTest.php
  test/Helper/PartialLoopTest.php
  test/Helper/Service/HeadTitleFactoryTest.php
  test/Helper/TestAsset/Aggregate.php
  test/Helper/TestAsset/IteratorWithToArrayTestContainer.php
  test/Helper/TestAsset/PartialLoopIterator.php
  test/Helper/TestAsset/PartialLoopIteratorWithToArray.php
  test/Helper/TestAsset/PartialLoopRecursiveIterator.php
  test/Helper/TestAsset/PartialLoopToArrayImplementor.php
  test/Helper/TestAsset/ToArray.php
  test/HelperPluginManagerCompatibilityTest.php
  test/Model/TestAsset/Variable.php
  test/Model/ViewModelTest.php
Labels: QA

#346 Set up mutation testing with `roave-infection-static-analysis-plugin`
  .gitattributes
  .github/workflows/continuous-integration.yml
  .gitignore
  .infection.json5.dist
  Makefile
  src/Exception/DomainException.php
  src/Exception/InvalidArgumentException.php
  src/Helper/Cycle.php
  src/Helper/HeadStyle.php
  src/Renderer/PhpRenderer.php
  src/Renderer/PhpRendererFactory.php
  test/HTML/TagTest.php
  test/Helper/CycleTest.php
  test/Helper/GravatarImageTest.php
  test/Helper/Service/AssetFactoryTest.php
  test/HtmlAttributesSetTest.php
  test/Renderer/PhpRendererFactoryTest.php
  test/Renderer/PhpRendererTest.php
  tools/infection/.gitignore
  tools/infection/composer.json
  tools/infection/composer.lock
Labels: BC Break, Enhancement, QA
