Repository laminas/laminas-view, pull requests merged in 2025-09, with the labels that each got.

#359 Documentation Changes for v3
  docs/book/v3/application-integration/stand-alone.md
  docs/book/v3/cookbook/setting-module-specific-layouts.md
  docs/book/v3/helpers/intro.md
  docs/book/v3/php-renderer.md
  docs/book/v3/quick-start.md
  docs/book/v3/template-resolvers.md
  docs/book/v3/view-event.md
  docs/book/v3/view-scripts.md
  mkdocs.yml
Labels: Documentation

#363 Replace `templatemap_generator.php` with a `Symfony\Console` command
  bin/templatemap_generator.php
  composer.json
  composer.lock
  phpunit.xml.dist
  psalm.xml.dist
  src/ConfigProvider.php
  src/Console/GenerateTemplateMapCommand.php
  src/Console/TemplateMapGenerator.php
  test/Console/GenerateTemplateMapCommandTest.php
  test/Console/TemplateMapGeneratorTest.php
  test/Console/templates/ignored.txt
  test/Console/templates/ignored/.gitkeep
  test/Console/templates/one.phtml
  test/Console/templates/sub/zero.phtml
  test/Console/templates/two.phtml
  test/bin/TemplateMapGeneratorTest.php
  tools/crc/config.json
Labels: BC Break, Enhancement

#366 Update Migration Guide with changes to Template Resolvers
  docs/book/v3/migration/v2-to-v3.md
Labels: Documentation, Enhancement

#365 Update Migration Guide with changes to `PhpRenderer`
  docs/book/v3/migration/v2-to-v3.md
Labels: Documentation

#367 Remove requirements for unused PHP extensions
  composer.json
  composer.lock
  tools/infection/composer.lock
Labels: Dependencies, QA

#368 Add make targets to check for unused dependencies
  .github/workflows/continuous-integration.yml
  Makefile
  tools/infection/composer.json
  tools/infection/composer.lock
Labels: QA

#371 Fixes order in navigation configuration for version 3 docs in `mkdocs.yml`
  mkdocs.yml
Labels: Bug, Documentation

#373 Allow for View Model Mutations Prior to Rendering
  src/Renderer/PhpRenderer.php
  src/View.php
  test/Helper/RenderChildModelTest.php
  test/ViewTest.php
Labels: Enhancement
